version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama-models:/root/.ollama
      - ./modelfiles:/modelfiles
    ports:
      - "11434:11434"
    working_dir: /modelfiles
    restart: always
